# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Hide the statusbar unless a message is shown.
# Type: Bool
c.statusbar.hide = True

# When to show the tab bar.
# Type: String
# Valid values:
#   - always: Always show the tab bar.
#   - never: Always hide the tab bar.
#   - multiple: Hide the tab bar if only one tab is open.
#   - switching: Show the tab bar when switching tabs.
c.tabs.show = 'multiple'

c.url.searchengines = {
        'DEFAULT': 'https://duckduckgo.com/?q={}',
        'yt': 'https://www.youtube.com/results?search_query={}',
        'red': 'https://reddit.com/r/{}'
        }

#play video in mpv (bind for normal mode)
config.bind('<Ctrl-v>', 'spawn mpv {url}')
